name:                FunkyChess
version:             0.1.0.0
github:              "https://github.com/Deltaphish/FunkyChess"
author:              "Joakim Anderlind; Lukas Andersson"
maintainer:          "joakimanderlind@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/FunkyChess#readme>

dependencies:
- base >= 4.7 && < 5
- parallel >= 3.2
- QuickCheck >= 2.13
# - Win32 >= 2.6

library:
  source-dirs: src

executables:
  TwoPlayer-exe:
    main:                Main.hs
    source-dirs:         TwoPlayer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunkyChess
    - parallel
#   - Win32 >= 2.6

  AI-exe:
    main:                Main.hs
    source-dirs:         AI
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunkyChess
    - parallel
#  - win32 >= 2.6
